name: "Contract Tests"
description: 'Runs contract tests against an SDK component.'
inputs:
  repo:
    required: false
    description: "Name of the test harness repo"
    default: 'sdk-test-harness'
  version:
    required: false
    description: "Version of the test harness"
    default: 'v2'
  test_service_port:
    required: true
    description: "Port of the component under test."
    default: '8123'
  test_harness_port:
    required: false
    description: "Port of the test harness."
    default: '8111'
  debug_logging:
    description: "Whether the test harness should print debug logs for failed tests."
    required: false
    default: 'false'
  extra_params:
    description: "Any other params to be passed to the test harness."
    required: false
  token:
    description: "Github token"
    required: false
    default: ''



runs:
  using: composite
  steps:
    - name: 'Run Contract Tests'
      shell: bash
      run: |
        curl ${{ inputs.token != '' && $AUTH_TOKEN || '' }} -s https://raw.githubusercontent.com/launchdarkly/${{ inputs.repo }}/main/downloader/run.sh | bash
      env:
        VERSION: ${{ inputs.version }}
        PARAMS: -url http://localhost:${{ inputs.test_service_port }} -port ${{ inputs.test_harness_port }} ${{ inputs.extra_params }} ${{ inputs.debug_logging == 'true' && '-debug' || '' }} -stop-service-at-end
        AUTH_HEADER: ${{ format('-H "Authorization: Token {0}"', inputs.token) }}
