name: Default Branch
description: "Checks if the current branch is the default branch"
inputs:
  token:
    description: 'GitHub API token.'
    required: true
outputs:
  value:
    description: 'The default branch of the repo.'
    value: ${{ steps.get-default-branch.outputs.value }}
  condition:
    description: "'true' if the current branch is the default branch of the repo."
    value: ${{ steps.get-default-branch.outputs.value == github.ref_name }}

runs:
  using: composite
  steps:
    - name: Get default branch
      id: get-default-branch
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        repo=$(echo "${{ github.repository }}" | cut -d '/' -f  2)
        owner=$(echo "${{ github.repository }}" | cut -d '/' -f  1)
        default_branch=$(gh api repos/$owner/$repo --jq '.default_branch')
        echo "value=$default_branch" >> $GITHUB_OUTPUT
