name: Lint PR title
# This is suitable for projects using release-please.
# Call this by uses: launchdarkly/gh-actions/.github/workflows/lint-pr-title.yml@main
# Use the following dispatch configuration:
# on:
#   pull_request_target:
#     types:
#       - opened
#       - edited
#       - synchronize

on:
  workflow_call:

jobs:
  main:
    name: Verify the PR title matches conventional commit spec.
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
