name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: 'This issue is marked as stale because it has been open for 30 days without activity. Remove the stale label or comment, or this will be closed in 7 days.'
          any-of-labels: 'Waiting for Feedback'
          labels-to-remove-when-unstale: 'Waiting for Feedback'
          days-before-stale: 30
          days-before-close: 7
